hw6 done
Maksym-Kartawcew/nodejs-hw2-rest-api pull request #5
Opened 2023-10-04 18:56 UTC by Maksym-Kartawcew

2023-10-04 20:57 UTC, ceREAL133 approved these changes

2023-10-04 20:58 UTC, ceREAL133 requested changes

2023-10-04 20:58 UTC, ceREAL133 commented on controllers/users-controller.js
> +    verificationCode: "",
токен має бути null

2023-10-04 20:58 UTC, ceREAL133 commented on controllers/users-controller.js
> +    verificationCode: "",
поміняйте і протестуйте

2023-10-04 21:26 UTC, Maksym-Kartawcew commented on controllers/users-controller.js
> +    verificationCode: "",
Поміняв, чи могли би Ви пояснити чим цей варіант кращий від пустого рядка? Бо не до кінця розумію  різницю

2023-10-05 12:11 UTC, ceREAL133 commented on controllers/users-controller.js
> +    verificationCode: "",
пустий рядок, це все ж строка, яка займає певне місце, а null- це прапорець для програми, що на це значення не треба навіть виділяти місця. Ну і плюс така вимога в тз до дз)

2023-10-05 12:11 UTC, ceREAL133 approved these changes

2023-10-12 17:35 UTC, merged